name: Auto-deploy Jekyll site to GitHub pages

on:
  push:
    branches:
      - main 
    paths-ignore:
      - 'README.md'
      - '_drafts/**'
      - '.github/**'
  repository_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight 

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
      - name: Build Jekyll site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'gh-pages'

